whamcloud/GUI

.babelrc
.travis.yml
package.json
readme.md

This patch adds code-coverage reporting
and a badge.

Add code coverage reporting

---

.vscode/launch.json

Add launch.json and a jest config so
we can debug jest in vscode.

Add launch.json

---

test/spec/iml/store/get-store-test.js

remove extra mocks

---

test/dom/iml/__snapshots__/dropdown-component-test.js.snap
test/dom/iml/__snapshots__/pagination-components-test.js.snap
test/dom/iml/__snapshots__/popover-test.js.snap
test/dom/iml/__snapshots__/window-click-listener-test.js.snap
test/dom/iml/alert-indicator/__snapshots__/alert-indicator-test.js.snap
test/test-utils.js

Updating snapshot generation
to return the DOM node
instead of innerHTML
makes for much more readable
snapshots.

Update snapshot generation

---

package.json

- Bump version to 6.1.0

---

.travis.yml

- Add skip_clean to travis file so that dist directory is published.

- Add skip_clean to travis file so that dist directory is published.

---

package.json

Bump version to 6.2.0

---

package.json

- Bump version to 6.2.1

---

source/iml/job-stats/job-stats-table-component.js
source/iml/old-gui-shim/old-gui-states.js
test/dom/iml/job-stats/job-stats-table-component-test.js
test/spec/iml/old-gui-shim/old-gui-states-test.js

- Update help links in old-gui states
- Update help link in job stats template

- Update help links

---

source/iml/storage/storage-states.js
test/spec/iml/storage/__snapshots__/storage-states-test.js.snap

- Fix help links in storage plugin states

- Fix help links in storage plugin states

---

package.json

- bump to version 6.2.3

---

package.json

- bump to version 6.2.4

---

source/iml/exception/exception-modal.js
test/spec/iml/exception/exception-modal-test.js

- Fixes Issue #106
- Changed the word "chroma" to "iml" in two places
- Ran pre-commit tests.
Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>

Change chroma-diagnostics to iml-diagnostics

---

source/iml/server/server-states.js
test/spec/iml/server/server-states-test.js

Fixes #113. Show tooltip on disabled upgrade button.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>

Fixes #113. Show tooltip on disabled upgrade button.

---

Makefile
iml-gui.spec
package-lock.json
package.json

Bump from 6.3.1 to 6.4.0

---

.travis.yml

Setup continuous deployment in Travis

Setup continuous deployment in Travis

---

.travis.yml

Install npm before deploying

---

Makefile
iml-gui.spec.in

Abstract the release to use Git commit num when unpublished.

---

include/.gitrepo
package-lock.json
source/iml/about/about-component.js
source/iml/app/app-states.js
test/spec/iml/app/__snapshots__/app-states-test.js.snap

remove more intel branding

---

Dockerfile
package.json

- update dockerfile to use babel.config.js

Fix docker

---

Dockerfile
Makefile
iml-gui.spec.in
package-lock.json

New dockerfile

---

flow-typed/sse.js
flow-typed/window.js
package-lock.json
package.json
source/iml/environment.js
source/iml/sse/sse-stream.js
test/spec/iml/sse/sse-stream-test.js

Fixes #162.
- Create the EventSource
- Handle disconnects
- Push messages down the stream

Create iml-warp-drive handler

---

source/iml/locks/locks-reducer.js
source/iml/store/get-store.js
test/spec/iml/locks/locks-reducer-test.js
test/spec/iml/store/get-store-test.js

Fixes #163.
- Create the locks reducer
- Tie locks reducer into store

Create reducer for locks

---

Makefile
iml-gui.spec.in
package-lock.json
package.json

Bump GUI to 6.4.2

---

source/iml/exception/exception-handler.js
source/iml/exception/exception-modal-reducer.js
source/iml/exception/exception-module.js
source/iml/modal.js
source/iml/store/get-store.js
test/spec/iml/exception/__snapshots__/exception-handler-test.js.snap
test/spec/iml/exception/exception-handler-test.js
test/spec/iml/exception/exception-modal-reducer-test.js
test/spec/iml/exception/exception-module-test.js
test/spec/iml/store/get-store-test.js

Create inferno exception modal

Create inferno exception modal

---

.travis.yml

Swap contents of deploy-copr and cd

Swap contents of deploy-copr and cd

---

source/iml/action-dropdown/action-dropdown-module.js
source/iml/hsm/hsm-module.js
source/iml/iml-module.js
source/iml/listeners.js
source/iml/old-gui-shim/iframe-shim-component.js
source/iml/sse/sse-handler.js
test/spec/iml/listeners-test.js
test/spec/iml/old-gui-shim/iframe-shim-component-test.js
test/spec/iml/sse/sse-handler-test.js

- Update iframe shim such that action messages work with old gui

- Add listeners to listen for actions and hsm actions

---

package-lock.json
package.json
source/iml/completionist/completionist-model-hook.js
source/iml/socket/socket-stream.js
source/iml/storage/storage-resource-histogram.js
source/iml/tooltip/tooltip.js

So that we only need to install them for building

Use prod deps

---

.copr/Makefile
.travis.yml

Use copr-node for building

---

source/iml/action-dropdown/action-dropdown-module.js
source/iml/action-dropdown/multi-dropdown.js
source/iml/corosync/configure-corosync.js
source/iml/file-system/file-system-component.js
source/iml/hsm/hsm-states.js
source/iml/mgt/mgt-component.js
source/iml/pacemaker/configure-pacemaker.js
source/iml/server/server-states.js
source/iml/status/status-records-component.js
test/dom/iml/mgt/mgt-component-test.js
test/spec/iml/action-dropdown/action-dropdown-test.js
test/spec/iml/hsm/hsm-states-test.js
test/spec/iml/server/server-states-test.js

The action dropdown has been refactored to handle different
contexts. This patch reflects the GUI side of this change.

Use new wasm layout

---

source/iml/action-dropdown/assets/css/action-dropdown.less
source/iml/file-system/file-system-detail-component.js
source/iml/file-system/file-system-detail-resolves.js
source/iml/file-system/file-system-module.js
source/iml/file-system/file-system-states.js
source/iml/iml-module.js
source/iml/mgt/mgt-component.js
source/iml/old-gui-shim/old-gui-resolves.js
source/iml/old-gui-shim/old-gui-states.js
source/iml/server/server-states.js
source/styles/main.less
test/dom/iml/mgt/mgt-component-test.js
test/spec/iml/old-gui-shim/old-gui-resolves-test.js
test/spec/iml/old-gui-shim/old-gui-states-test.js
test/spec/iml/server/server-states-test.js

Implement fs-detail page

---

package-lock.json
package.json
source/iml/app/app-resolves.js
test/spec/iml/app/app-resolves-test.js

Remove health stream

---

source/iml/route-names.js
source/iml/tree/tree-fs-item-component.js
test/dom/iml/tree/tree-fs-item-component-test.js
test/spec/iml/old-gui-shim/old-gui-states-test.js

fixup filesystem detail link on treeview

---

package-lock.json
package.json
source/iml/exception/exception-handler.js
test/spec/iml/exception/exception-handler-test.js
test/spec/iml/server/__snapshots__/select-server-profile-step-test.js.snap

Remove srcmap-reverse code

---

source/iml/dashboard/dashboard-resolves.js
source/iml/dashboard/dashboard-states.js
source/iml/file-system/file-system-component.js
source/iml/file-system/file-system-detail-component.js
source/iml/file-system/file-system-module.js
source/iml/file-system/file-system-resolves.js
source/iml/file-system/file-system-states.js
source/iml/metrics/metric-polling.js
test/spec/iml/dashboard/__snapshots__/dashboard-resolves-test.js.snap
test/spec/iml/dashboard/dashboard-resolves-test.js
test/spec/iml/dashboard/dashboard-states-test.js
test/spec/iml/file-system/file-system-states-test.js
test/spec/iml/metrics/__snapshots__/metric-polling-test.js.snap
test/spec/iml/metrics/metric-polling-test.js

Poll metrics on dashhhboard, filesystem, and filesystem detail page.

GH-1285 client_count bytes_{free,total}, files_{free,total} do not live-update

---

source/iml/metrics/metric-polling.js

- Add trailing slash to prevent redirect

- Remove unnecessary console statement

---

.travis.yml
source/iml/global.js
test/spec/iml/server/__snapshots__/select-server-profile-step-test.js.snap

Update wasm_bindgen assignment
