whamcloud/GUI

- source/iml/file-system/file-system-dispatch-source.js
- test/spec/iml/file-system/file-system-dispatch-source-test.js
Fixes #3.
In https://github.com/intel-hpdd/GUI/blob/c1d8fd597d777bbd49aeee830a6b37ca10e5bb3c/source/iml/file-system/file-system-dispatch-source.js#L47 The jsonMask is inside the qs instead of above it. This will cause more data to be fetched then we want, as fs is one of the larger endpoints.
Move jsonMask up.
> move jsonMask prop up for fs api dispatch call.

- source/iml/lnet/lnet-dispatch-source.js
- source/iml/server/server-detail-resolves.js
- test/spec/iml/lnet/lnet-dispatch-source-test.js
- test/spec/iml/server/server-detail-resolves-test.js
We currently are using `fp.find` in a few resolves where we are not expecting to deal with the `maybe` type.
Switch those resolve to use `Array.prototype.find` instead.
> Fix find usage in some resolves.

- source/iml/alert-indicator/alert-indicator.js
Fixes #34.
The alert indicator needs to filter by affected id. It currently is not
due to us not ajusting function arity when removing currying.
> alert-indicator not filtering.

- source/iml/command/wait-for-command-completion-service.js
- source/iml/lnet/configure-lnet.js
- source/iml/server/create-host-profiles-stream.js
- source/iml/server/select-server-profile-step.js
- source/iml/server/server-detail-resolves.js
- test/spec/iml/command/wait-for-command-completion-service-test.js
- test/spec/iml/server/create-host-profiles-stream-test.js
- test/spec/iml/server/select-server-profile-step-test.js
Fixes #35.
waitForCommandCompletion was not updated to unary functions when currying was removed.
> Unable to update LNet / Corosync

- source/iml/popover.js
- source/iml/popover.less
- test/dom/iml/__snapshots__/popover-test.js.snap
- test/dom/iml/popover-test.js
As we move to using inferno, we need to
re-implement components.
Re-do the popover component in inferno.
In addition, add tests.
A follow-up patch will replace the existing popover.
> Implement Popover using Inferno

- package.json
- webpack.config.js
- yarn.lock
Installing the library: clean-webpack-plugin
allows for the elimination of unwanted files during webpack builds.
- Added the clean-webpack-plugin library
- Modified the webpack.config.js file to specify what files to purge
> Using webpack with watch generates extra files that are not cleaned up.

- source/iml/alert-indicator/alert-indicator.js
- source/iml/popover.js
- source/iml/window-click-listener.js
- test/dom/iml/__snapshots__/window-click-listener-test.js.snap
- test/dom/iml/alert-indicator/alert-indicator-test.js
- test/dom/iml/popover-test.js
- test/dom/iml/window-click-listener-test.js
- test/test-utils.js
- yarn.lock
We have a pattern (that seems to be shared by bootstrap components) where we
need to listen to a click on the window
to trigger closing a component.
As an example, consider a dropdown.
Clicking the dropdown button should open it.
Clicking anywhere after the dropdown is open
should close it.
This work is needed as part of #31.
> Create WindowClickListener component

- source/iml/dropdown-component.js
- source/iml/pagination-components.js
- source/styles/main.less
- test/dom/iml/__snapshots__/dropdown-component-test.js.snap
- test/dom/iml/__snapshots__/pagination-components-test.js.snap
- test/dom/iml/dropdown-component-test.js
- test/dom/iml/pagination-components-test.js
- test/dom/iml/window-click-listener-test.js
Create some pagination components in
Inferno that are reusable across
the GUI.
In particular, create components
that do pagination, number or entry selection,
and listing table info.
We can use the meta field of the
API response to glean the needed info.
This is needed as part of #31 
> Create pagination components

- source/iml/api-transforms.js
- test/spec/iml/api-transforms-test.js
Add a `filterSame` transform.
It will take a value and only return true when
the previous and current value are different
by reference.
This is useful for filtering immutable values.
This is needed for #31 
> Add filterSame transform.

- package.json
- source/iml/charting/area.js
- source/iml/charting/axis.js
- source/iml/charting/chart.js
- source/iml/charting/legend.js
- source/iml/charting/line.js
- source/iml/charting/types/line/get-line.js
- source/iml/charting/types/line/line-directive.js
- source/iml/charting/types/line/line-module.js
- test/dom/iml/charting/__snapshots__/area-test.js.snap
- test/dom/iml/charting/__snapshots__/axis-test.js.snap
- test/dom/iml/charting/__snapshots__/chart-test.js.snap
- test/dom/iml/charting/__snapshots__/legend-test.js.snap
- test/dom/iml/charting/__snapshots__/line-test.js.snap
- test/dom/iml/charting/area-test.js
- test/dom/iml/charting/axis-test.js
- test/dom/iml/charting/chart-test.js
- test/dom/iml/charting/legend-test.js
- test/dom/iml/charting/line-test.js
- test/dom/iml/charting/types/line/get-line-test.js
- test/dom/iml/charting/types/line/line-directive-test.js
- test/test-utils.js
- yarn.lock
Implement some chart components for inferno.
This will allow us to declaratively create charts using html. Example (pseudocode following):
```
<Chart>
<Axis />
<Line />
</Chart>
```
There are a few rules that make this easier.
1. Only pass changes downward, no handlers for
chart updating on the chart component itself
2. We skip scales as a component. They are
the variant part of making a chart in many
cases, we can just create them inline during
usage.
3. Each component will pass it's props, and useful
parent props to their children. This ensures that
scales and such are propagated where they should be.
> Implement Chart components for inferno.

- source/iml/dashboard/dashboard-states.js
- source/iml/file-system/file-system-states.js
- source/iml/help-mapper/help-mapper-directive.js
- source/iml/hsm/hsm-states.js
- source/iml/job-stats/job-stats-states.js
- source/iml/logs/log-states.js
- source/iml/mgt/mgt-states.js
- source/iml/server/server-states.js
- source/iml/status/status-states.js
- test/dom/iml/help-mapper/help-mapper-directive-test.js
- test/spec/iml/dashboard/dashboard-states-test.js
- test/spec/iml/file-system/file-system-states-test.js
- test/spec/iml/hsm/hsm-states-test.js
- test/spec/iml/job-stats/job-stats-states-test.js
- test/spec/iml/logs/log-states-test.js
- test/spec/iml/mgt/mgt-states-test.js
- test/spec/iml/server/server-states-test.js
- test/spec/iml/status/status-states-test.js
Now that online help has been packaged into manager for lustre
dependencies we can update the help mapper to point to the new locations
in online help.
> Integrate Online Help

- source/iml/api-transforms.js
- source/iml/dashboard/base-dashboard-chart-resolves.js
- source/iml/dashboard/dashboard-states.js
- source/iml/dashboard/server-dashboard-resolves.js
- source/iml/dashboard/target-dashboard-resolves.js
- test/spec/iml/dashboard/base-dashboard-chart-resolves-test.js
- test/spec/iml/dashboard/dashboard-states-test.js
- test/spec/iml/dashboard/target-dashboard-resolves-test.js
- test/spec/iml/job-stats/job-stats-resolves-test.js
- webpack.config.js
As discovered in https://github.com/intel-hpdd/intel-manager-for-lustre/issues/198
There are a few issues appearing with our charts. They are:
1. Target dashboard is not currently usable.
2. Server dashboard is not printing specific server.
This is due to us not unwrapping maybe types returned by find,
and not casting the API search id to an int during the find call.
> Fix chart issues

- source/iml/hsm/add-copytool-modal.js
- test/spec/iml/hsm/add-copytool-modal-test.js
Fixes #64.
- Typing a number in the archive field does not remove the validation
message. This patch removes the pattern property as it is not needed.
This will allows the field to validate properly, removing the
validation message when an integer is entered. Letters cannot be typed
into the input field.
> Fix Archive Number

- source/iml/pdsh/assets/css/pdsh.less
Issue: https://github.com/intel-hpdd/GUI/issues/4
On the Configuration > Servers > Add More Servers
The popup that lists the desired hostnames to add was showing up behind other elements.
- Changed the .popover css z-index value to correct the stack order for the element.
Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>
> Popover is popping under on server status page

- source/iml/storage/storage-detail-component.js
Fix hanging dashboard streams
- When navigating away from the dashboard page all of the chart streams
continue to pipe data over the websocket. The sockets should close
after leaving the dashboard page. The problem was in flatMapChanges.
This patch will update to flatMapChanges@1.0.4 to ensure that the
source$ is destroyed when appropriate. This will prevent the chart
streams from persisting between pages.
> Fix dashboard streams

- package.json
- yarn.lock
- Downgrade file-loader to 0.11.2 as the latest version is causing the fonts to be loaded with an object instead of a url.
> Downgrade file-loader to 0.11.2

- source/iml/file-system/file-system-dispatch-source.js
- test/spec/iml/file-system/file-system-dispatch-source-test.js
File information is not being displayed on the dashboard. The files
total and files used information should be displayed on the dashboard.
> Fixes #94.

- source/iml/lnet/lnet-options.js
- test/spec/iml/lnet/__snapshots__/remove-used-lnet-options-filter-test.js.snap
- test/spec/iml/lnet/remove-used-lnet-options-filter-test.js
Fixes #101
Fox-13 shows a customer who needs support for 32 nids. We would like to put in a better
interface but for now, we will add support for 50 nids.
> Increase NIDs on server detail page

- source/iml/file-system/file-system-dispatch-source.js
- test/spec/iml/file-system/file-system-dispatch-source-test.js
The filesystem type always displays as "managed" on the dashboard. This
is because the "immutable_state" property was not included in the json
mask. After adding this property, the filesystem type lable now shows
"monitored" when working with a monitored filesystem.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>
> Fix Filesystem type label

- source/iml/server/select-server-profile-step.js
- test/spec/iml/server/__snapshots__/select-server-profile-step-test.js.snap
- test/spec/iml/server/select-server-profile-step-test.js
Fixes https://github.com/intel-hpdd/intel-manager-for-lustre/issues/406
Set monitored mode to be the first profile on the select profile screen.
> Change order of profiles

- package-lock.json
- package.json
- source/iml/display-date.js
- source/iml/iml-module.js
- source/iml/logs/log-query-component.js
- source/iml/logs/log-states.js
- source/iml/logs/log-table-component.js
- source/iml/status/status-records-component.js
- source/iml/tz-picker/tz-picker.js
- test/dom/iml/__snapshots__/display-date-test.js.snap
- test/dom/iml/display-date-test.js
- test/dom/iml/message-substitution/log-table-component-test.js
- test/spec/iml/logs/log-query-component-test.js
- test/spec/iml/logs/log-states-test.js
The timestamps on the logs page are being displayed in UTC only. Give
the user the option of selecting local or UTC time.
> Make time configurable on the Logs page

- source/iml/command/assets/css/command-modal.less
Looking at output in the command modal is difficult due to it being so
narrow.
Widen it to 95% of the view width.
> Widen command modal.

- flow-typed/angular.js
- source/iml/extend-scope-module.js
We are using Seamless Immutable to make sure all data persisted
to the store is immutable, and then removing the immutability before we
cross boundaries where data needs to be mutable, i.e. Inferno or
Angular.
Instead of unwrapping all boundaries manually, we can cover most angular
boundaries by adding a check into `propagateChange` that will ensure
any Seamless Immutable wrapped data that is received becomes mutable
again.
Fixes #176.
> Make items passing through propagateChange mutable

- source/iml/hsm/hsm-fs-controller.js
- test/spec/iml/hsm/hsm-fs-controller-test.js
- The stream in fs-hsm is comparing a number to a string representation of a number, which will never be equal.
Therefore, the action button will never display. This patch will parse the string into an integer. It also takes out
fp.map as there is no need to use a maybe here.
> Fix fs-hsm action dropdown

- source/iml/sse/sse-stream.js
- test/spec/iml/sse/sse-stream-test.js
Testing backoff for server send events currently works when it receives 502's. However, if nginx is stopped or the
chroma manager is restarted, the retry count will skyrocket exponentially. This was due to the event stream being closed
inside the setTimeout. To fix this, the close was moved outside of the timeout and only "next" is called inside the
timeout to turn the generator.
> Fix Backoff for SSE

- source/iml/app/app-resolves.js
- source/iml/app/app-states.js
- test/spec/iml/app/__snapshots__/app-states-test.js.snap
- test/spec/iml/app/app-resolves-test.js
- test/spec/iml/app/app-states-test.js
The app should not load until data is received from the event stream. This patch will add a resolve on the sse to make
sure data is received from the store before the app is loaded.
> Wait for SSE before loading the app

- source/iml/tooltip/assets/css/tooltip.less
So it does not overlay modals.
> Lower z-index of tooltip.

- source/iml/command/command-handlers.js
- source/iml/file-system/file-system-detail-component.js
- source/iml/listeners.js
Fixes #1100.
Clicking the Enable / Update or Delete buttons within Stratagem config should show the command modal. This way the user can be notified of progress.
> Enable / Update / Delete stratagem config should show command modal

- source/iml/file-system/file-system-reducer.js
- source/iml/server/server-actions.js
- source/iml/server/server-controller.js
- source/iml/server/server-reducer.js
- source/iml/server/server-resolves.js
- source/iml/server/server-states.js
- source/iml/target/target-reducer.js
- test/spec/iml/server/server-actions-test.js
- test/spec/iml/server/server-controller-test.js
- test/spec/iml/server/server-resolves-test.js
- test/spec/iml/server/server-states-test.js
Fixes #1237.
Description:
The available updates button remains disabled in an upgrade to 5.1. This is due to warp-drive not picking up changes for the computed property member_of_active_filesystem (which is derived mostly from the fs table). It seems like the most straightforward way to solve this is to check for server fs membership in the GUI by joining the data sets together.
> Available updates button disabled

- source/iml/api-transforms.js
- source/iml/dashboard/base-dashboard-controller.js
- source/iml/dashboard/dashboard-controller.js
- test/spec/iml/api-transforms-test.js
- test/spec/iml/dashboard/base-dashboard-controller-test.js
- test/spec/iml/dashboard/dashboard-controller-test.js
- test/spec/iml/target/filter-target-by-fs-test.js
Fixes #232.
When selecting the filter on the dashboard page and selecting a filesystem the gui will crash. This happens because the
data format has changed from an array of objects to a hash in which each key points to an object. The data is
essentially the same, but in a different format. This caused the filter to blow up when selecting a filesystem,
or applying a target. In addition, once the error was resolved, all filesystems were being displayed even
though an individual one was selected. This happened because the dashboard controller was not filtering out
filesystems based on the filesystem id that was selected. This patch resolves each of these problems.
> GH-232 Selecting filesystem from dashboard dropdown causes error

- source/iml/server/server-controller.js
The active servers are not being passed into `toggleDisabled` when getting the selected hosts. Pass the active servers
when calling toggleDisabled.
> Fix error when toggling update servers button
